### ISSUE TITLE
Cheat_no_lockpicking won't revert

### ISSUE THREAD

**Issue by Barerock** [pryans/kcd-cheat#13]
How do I revert this command? I turned it on because I got fed up with encountering early game "very hard" chests. Turning on the individual door and stash commands and restarting doesn't fix it, and the Nexus forum doesn't have any info on it either. Looking through all 1600 posts is unfeasible, I looked through pages 1-12.

**Comment by pryans** [comment]
Those commands swap out a function in memory to bypass the mini game. This means it can't affect your save game; that just isn't possible.

I would guess you're running the cheat_no_lockpicking command automatically when the game starts from autoexec file, through another mod, or there is a bug with another mod.

Uninstall the cheat mod. If "no lock picking" stops then you're running the command somehow when the game starts.

**Comment by Barerock** [comment]
Weirdly it did revert after restarting, however, the chest I was testing it on (hadn't opened it at all) was a normal reinforced looking chest that I'd assume would be locked (in a bandit camp) so either the command unlocked it in an AOE from the one I used it on, or it was never locked. I was fooled!

Thanks for the quick response!
