### ISSUE TITLE
Cheats loaded, not working

### ISSUE THREAD

**Issue by WilliamiWallace** [pryans/kcd-cheat#14]
Console shows all cheat files are loaded, but only cheat_phys cheats are showing up when typing cheat (tab) and no other cheats work.

**Comment by pryans** [comment]
I have no idea how that would even be possible. All the commands are loaded with the same code. 

Have you tried to temporarily disable other mods? 

What happens if you just run a command even through it doesn't show up with tab completion, like 
`cheat_add_money amount:123` ?

**Comment by WilliamiWallace** [comment]
tried a couple of different solutions believe its a conflict with another mod so far only issues with the Architect mod, ive just disabled that mod thanks for the help

**Comment by Harlekin13** [comment]
if the mod relies on the old cheat console commands, it won't work, they got changed for some reason.

seems some work in 1.9.6 still...
