### ISSUE TITLE
Quest reset

### ISSUE THREAD

**Issue by Csimbi** [pryans/kcd-cheat#15]
Hello,
seems you are well versed in the LUA subsystem of KCD.
Would you be able to create some scripts to reset/restart broken quests?
Yeah, I know it's not a cheat, but it's highly sought after.
I am stuck with the 'missing Reeky' bug in the 'On the Scent' quest.

I've invested tons of time on Hardcore and starting a new game to fix a bug (which is not even guaranteed, btw) is something I would rather avoid.
I saw some mods on Nexus that supposedly do this but all of them appear to be defunct.
The developer offers zero support - I guess there is a good reason why they abandoned this bug-infested game.

I thought with your skills you might be able to find a way to fix borked quest.

Thank you for considering!

**Comment by AndreLouisIssa** [comment]
`cheat_eval QuestSystem.ResetQuest( QUEST_NAME )`

but choose QUEST_NAME to specify the quest you want to reset, here's the localised names by quest name
https://wiki.fireundubh.com/kingdomcome/quests

**Comment by Banshee2k2** [comment]
need help with KCD2
reset quest with console, cant find the quest names on wiki
