### ISSUE TITLE
Zip File is wrong packaged

### ISSUE THREAD

**Issue by wilecoyote** [pryans/kcd-cheat#23]
The localization for the keybindings must not be in the data folder, it will not work if you try to load it from there.

The package must look like:

Root\Data
Root\Data\data.pak
Root\Localization
Root\Localization\English_xml.pak
Root\Localization\German_xml.pak
Root\mod.manifest

**Comment by pryans** [comment]
Should be fixed. See 1.46

**Comment by wilecoyote** [comment]
Exclude the Localization and \Data\Libs\Config folder from the NOKEYS version. They are only necessary for the keybinds.

**Comment by pryans** [comment]
The Config folder is empty on the NOKEYS version.
If the Localization folder isn't empty does that cause a problem?

**Comment by pryans** [comment]
I made these changes as well and put them on github.
https://github.com/pryans/kcd-cheat/releases/tag/1.47

**Comment by wilecoyote** [comment]
Looks perfect to me :)

**Comment by pryans** [comment]
ok thanks for the help.
