### ISSUE TITLE
Localization files

### ISSUE THREAD

**Issue by wilecoyote** [pryans/kcd-cheat#24]
I'm so sorry. I only checked the NOKEYS version before. When I updated the mod through Vortex Mod Manager I noticed, that the localization is not loaded.

The folders **English_xml** and **German_xml** within the **Localization** folder must be .pak files in the zip. The game can't load plane xml files.

**Comment by pryans** [comment]
Ok, I didn't even notice the pak extension.

From the other issue you have:
Root\Localization\English_xml.pak
Root\Localization\German_xml.pak

Is there any internal structure to them? do the xml files just sit in the root of the pak file?

**Comment by wilecoyote** [comment]
No, the specific language folders are only needed for the creation of the pak files when you pack it by hand. The xml files can just sit in the root of the pak files, Only the naming of the pak files is essential

**Comment by pryans** [comment]
Ok should be fixed.
https://github.com/pryans/kcd-cheat/releases/tag/1.48

**Comment by pryans** [comment]
nexus is updated, let me know if it works. thanks.

**Comment by wilecoyote** [comment]
Updated with Vortex Mod Manager and it works correctly now.

**Comment by pryans** [comment]
ok thanks
