### ISSUE TITLE
Quest Reset Questions

### ISSUE THREAD

**Issue by BattleshipPotemkin** [pryans/kcd-cheat#27]
I saw that quest reset was available in this mod but following instructions given in another issue here on the github didnt work for me
the command im using is this cheat_eval QuestSystem_ResetQuest ( q_church_construction )  if there is any problem with spaces and capital letter i would like to know, thanks.

**Comment by pryans** [comment]
I do not know anything about the quest commands. For cheat_eval I would avoid using space since i might break the parser, I haven't look at it in years though.

I suggest something like:
cheat_eval QuestSystem.ResetQuest('q_church_construction')

**Comment by AndreLouisIssa** [comment]
note also that you can put string literals next to a function without parenthesis in lua, so `cheat_eval QuestSystem.ResetQuest'q_church_construction'` should also work.

But resetting quests in this game is actually really finnicky so I don't think this will work for you anyway, I was only able to make good use of the QuestSystem for minor side quests that don't affect much of the world (like the one where you have to return the sacred bowl to the guard near the monastery)
