### ISSUE TITLE
Open Question: Improvements/Workarounds for cheat_eval

### ISSUE THREAD

**Issue by AndreLouisIssa** [pryans/kcd-cheat#32]
`cheat_eval` has two major issues:
* it gives no feedback on the validity of the lua being run, so it's very hard to debug, especially syntax errors.
* some symbols used by lua code can't be entered into the console/command (`~`, `=`, `;`).

And some inconveniences (personally):
* it's too long to type if trying to quickly explore the in-game lua using it.
* `function` is too long if you have to type it a lot to make helpers or to call anonymously.
* `print` goes to stdout instead of to the console
*  return values / expressions don't get printed

I have tried to rectify all this with my personal code in `autocheat.lua`:
```lua
function table.pack( ... )
  return { n = select( "#", ... ), ... }
end

function table.unpack( t, s, e, ... )
	return unpack( t, s or 1, e or t.n, ... );
end

function print( ... )
	local t = table.pack( ... )
	for i = 1, t.n, 1 do
		t[ i ] = tostring( t[ i ] )
	end
	return cheat:log( "$5" .. table.concat( t, '\t' ) )
end

function range( lo, hi, st )
	if hi == nil then
		hi = lo
		lo = 1
	end
	st = st or 1
	return function( _, i )
		i = i and i + st or lo
		if i > hi then return nil end
		return i
	end, nil, nil
end

local manglemap = {
	['!'] = '=', -- the example screenshots used `:` but this prevents using object method call syntax
	['&'] = ';',
	['%^'] = '~',
	['@'] = 'function'
}

local function mangle( s )
	for k, v in pairs( manglemap ) do
		s = s:gsub( k, v )
	end
	return s
end 

function eq( a, b )
	return a == b
end
function leq( a, b )
	return a <= b
end
function geq( a, b )
	return a >= b
end

function nop( ... ) return ... end

function set( k, v, t )
	( t or _G )[ k ] = v
end
function lset( k, v, l )
	l = l and l + 1 or 2
	local f = debug.getinfo( l, 'f' ).func
	local i = 1
	repeat
		local name = debug.getlocal( l, i )
		if name == k then
			debug.setlocal( l, i, v )
			return true
		end
		name = debug.getupvalue( f, i )
		if name == k then
			debug.setupvalue( f, i, v )
			return true
		end
		i = i + 1
	until not name
	return false
end

function relay( fs, ... )
	local ret = table.pack( ... )
	for i = 1, fs.n or #fs, 1 do
		ret = table.pack( fs[ i ]( table.unpack( ret, 2, ret.n ) ) )
		if ret[ 1 ] then
			return table.unpack( ret, 2, ret.n )
		end
	end
	return table.unpack( ret, 2, ret.n )
end

function eval( s, ... )
	local func, err = loadstring( "return " .. s )
	if not func then
		func, err = loadstring( s )
	end
	if not func then return cheat:log( "$4" .. err ) end
	local ret = table.pack( pcall( func, ... ) )
	if not ret[1] then return cheat:log( "$4" .. ret[2] ) end
	if ret.n <= 1 then return end
	for i = 2, ret.n, 1 do
		ret[ i ] = tostring( ret[ i ] )
	end
	return cheat:log( "$5" .. table.concat( ret, '\t', 2, ret.n ) )
end
cheat:createCommand( "..", "eval(%line)", nil, "Executes the given Lua code." )

function meval( s, ... )
	return eval( mangle(s), ... )
end
cheat:createCommand( ".", "meval(%line)", nil, "Executes the given Lua code, mangled to be possible/easier to type in the console." )
```

The code is imperfect and infects the globals, it's fine for my personal use but to be properly included in this project it would have to be changed (that's why this is not a Pull Request)

How best can we resolve these issues for the public version?

Here are some example screenshots using this file:

![expression and return values,  assignment and multiline](https://media.discordapp.net/attachments/699492126039212152/1001498469506224258/unknown.png)
![range iterator instead of numerical for loop](https://media.discordapp.net/attachments/699492126039212152/1001500456331260074/unknown.png)
![assignment between commands](https://media.discordapp.net/attachments/699492126039212152/1001504647401439242/unknown.png)
![function alias](https://media.discordapp.net/attachments/699492126039212152/1001510754232578058/unknown.png)
![syntax error](https://media.discordapp.net/attachments/699492126039212152/1001518698403737701/unknown.png)

And here's an example where it's not working properly:
![fail](https://media.discordapp.net/attachments/699492126039212152/1001518650357989416/unknown.png?width=1147&height=27)
I do have that launch option already anyway, so this is very odd.

**Comment by pryans** [comment]
Couple of points.

1. Add these functions into the global namespace is dangerous and will probably break other mods.
2. We might be pushing cheat_eval to the limits. I think cryengine allows you to just execute lua code in the console if you enable it. I'm not familiar with how this is done but I heard of this a while ago after making cheat_eval.
3. I do not play the game, own any DLCs, or even have it installed. So performing major dev work on the mod is not something I can do right now. I can review code, talk about ideas, merge code, etc, but the PRs need to be coded/testing by others for now.

Possible solutions to integrate these functions:

1: Put them in the cheat namespace.

2: Put them in the cheat namespace and as a convenience inject the "cheat:" namespace in front of a set of keywords before executing the eval string so the functions are in the cheat namespace but the namespace isn't needed for them to work.

3: Place the functions in a file cheat_core_debug_functions.lua. Make a console command to load this file. This wouldn't be automatically loaded. You could either load it manually when you need to debug or use autocheat to load it. This avoids breaking other mods out of the box. The console command documentation could have a warning explaining the risks.

As long as the global namespace isn't impacted by default when the mod loads I think we are good.

**Comment by AndreLouisIssa** [comment]
The problem for me is that `setfenv` doesn't work on calls propagated from the affected function, so I can't make the eval context consider things globals that the rest of the lua doesn't, without even more mangling of the text (which is really tiresome to code in a way that doesn't break string literals or otherwise 'surprise' the user with malformed output, so I won't even try). 

I managed to make a lua context system for Hades (lua 5.2) that does propagate environment changes to calls within that context, and I used that to make a REPL with lua aliases, but I've yet to try it on lua 5.1 and all the code for that assumes the rest of the libraries I made for that so I'd have to unroll what I need to remove that dependency, and there may be subtle assumptions that are routinely broken in this game's context that I safely ignored for Hades. I do have to replace a part of the registry to do it and the globals become a proxy via their metatable, so anything doing raw interactions with the globals will fail here.

Another way to do it would be to assume there aren't any thread unsafe operations going on in this implementation of lua (haven't looked it up) and so when we enter the `eval` call we store the old environment, then replace it entirely from the registry with a copy that we inject with our overwritten globals, then when the `eval` call exits we restore the old environment in the registry. To be clear this is only safe if all the code interfacing with the lua state/registry at this time is the same OS thread. Also (due to messing with the registry) this could have very odd consequences if anything is using `require` (Hades does not have `require`, so I've never tested this)

**Comment by AndreLouisIssa** [comment]
So for simplicity I'll take a modified form of 

"2: Put them in the cheat namespace and as a convenience inject the "cheat:" namespace in front of a set of keywords before executing the eval string so the functions are in the cheat namespace but the namespace isn't needed for them to work."
but instead of mangling the text to map it to the namespace I'll just make the metatable `__index` of the env I `setfenv` map its values to a wrapped call of the cheat object

so `print` is `function( ... ) return cheat:print( ... ) end` etc (or perhaps `cheat:debug_print`)

this is better than 2 since it will not affect string literals or member accesses or other namespace accesses, it will only affect the code directly put into the eval not the insides of any functions called so that's the same semantics as mangling the text without the bugs.

The main issue I have (that the previous comment is referring more generally to) is that say I call a function that prints a bunch of stuff, unless that function was defined in an env that used my print, when it goes to print it will not show up in the console. In python I can rectify this by using a context manager to redirect the stdout filestream to a StringIO object, then breaking the output by newlines and serving them as separate log entries, but that's not easily done in lua so instead I would temporarily/context sensitively override print and hope the function is appealing to a global to do so.

In this case it might not be an issue because all your helpers will probably be defined either in the console (so using the eval's env as upvalues) or made specifically for use with this game so you'd naturally print to console when you make that helper.
