### ISSUE TITLE
invincibillity buff

### ISSUE THREAD

**Issue by eikufr** [pryans/kcd-cheat#37]
I dont know how to remove the invincibillity buff

**Comment by pryans** [comment]
What command did you use?


If you used cheat_add_buff_immortal then the documentation says:

[size=4][b]cheat_add_buff_immortal[/b][/size]
Adds buffs to make the player immortal. Use cheat_remove_buff_immortal to remove this.

[b]Examples:[/b]
 Add immortality:
 cheat_add_buff_immortal

[size=4][b]cheat_remove_buff_immortal[/b][/size]
Removes the buffs making the player immortal.

[b]Examples:[/b]
 Remove immortality:
 cheat_remove_buff_immortal

**Comment by eikufr** [comment]
I used the invincibillity potion

**Comment by pryans** [comment]
I have no idea what that is or what that has to do with this mod.

**Comment by eikufr** [comment]
In the directory where there are all the items id there is a potion named "Test Potion: Invincible" i drank it and now im forever invincible

**Comment by pryans** [comment]
You should always make a backup of you save before trying risky mod stuff.

I don't know what the potion does, that isn't something this mod added, I think that was part of the base game and probably created by the game devs.

**Option 1**
There might be overlap between the test potion and cheat_add_buff_immortal. So adding and removing the immortal buff might fix the problem.
1. Backup your save
2. run cheat_add_buff_immortal
3. run cheat_remove_buff_immortal

**Option 2**
It might add a selection of perks. You could view your perks and see if you can identify the perks that were added.
1. Backup your save
2. Find the perk IDs with cheat_find_perks
3. Remove them with cheat_remove_perk

See https://forums.nexusmods.com/index.php?/topic/6410541-cheat/page-221#entry121608594 for the perk commands

**Comment by eikufr** [comment]
Ok , I will try it thanks for your help.

**Comment by wilecoyote** [comment]
Following command should work: **cheat_remove_buff id:4add60ab-9015-4e56-9f7a-cb19345d6d49** or
**cheat_remove_buff id:test_invincible**

@pryans I think you can close this issue as it has nothing to do with your mod
