### ISSUE TITLE
Porting fly mode, free cam amd 3rd person camere mode from debug version of the game?

### ISSUE THREAD

**Issue by Aztec2012** [pryans/kcd-cheat#44]
Porting fly mode, free cam amd 3rd person camere mode from debug version of the game? Its possible?

**Comment by pryans** [comment]
I assume you're talking about these https://www.nexusmods.com/kingdomcomedeliverance/mods/864 mod tools?
I don't actively develop this mod anymore but I did take a look inside the 6GB zip file though to see what is going on. 

The mod tool comes with an actionmap called "debug" inside Data_reference\Libs\config\defaultProfile.xml
You can see here the keybindings for the these functions you're talking about.
```
<actionmap name="debug" version="22">
	<!-- debug keys - move to debug when we can switch devmode-->
		<action name="flymode" onPress="1" noModifiers="1" keyboard="f3" />
		<action name="godmode" onPress="1" noModifiers="1" keyboard="f4" />
		<action name="toggleaidebugdraw" onPress="1" noModifiers="1" keyboard="f11" />
		<action name="togglepdrawhelpers" onPress="1" noModifiers="1" keyboard="f10" />
		<action name="debug" onPress="1" keyboard="7" />
		<action name="thirdperson" onPress="1" noModifiers="1" keyboard="f1" />
		<action name="ui_start_pause_editor" onPress="1" keyboard="pause"/>
		<action name="ui_start_main_menu" onPress="1" keyboard="shift pause"/>
	 <!-- debug keys - end -->
```

I searched through all ~19,000 files in the zip file for references to "flymode". The only useful hit I got was in bin\win64releasedll\entitymodule.dll which is obviously a C++ DLL. I'm guessing the debug function you're interested in are either coded into this DLL or are part of a special build of cryengine. They don't appear to be scripts so there isn't anything I can do to port the functionality to a mod.

Make a backup of your game files and saves before trying this.

My only idea would be to copy <action name="flymode" onPress="1" noModifiers="1" keyboard="f3" /> into your default profile and then copy kingdomcome.exe and entitymodule.dll (from the zip's bin\win64releasedll folder) into your game folder and see if you can get it to work that way. It might be better to just copy all the bin files to start with. You might then be able to load a save game and use the debug functions via your new keybinds.

Good Luck
