### ISSUE TITLE
Request: query/dump RPG parameters

### ISSUE THREAD

**Issue by Csimbi** [pryans/kcd-cheat#45]
Hello,
While looking for some tools to aid mod devs, I found this mod.
Very nice tool!

I would like to make a request, if I may.
Namely, add two simple calls.
 - One that takes a string as a parameter, e.g., "AimSpreadMax", and then print the current value to the console. I.e. local x = RPG.<param> and then print x.
 - And another that dumps every single parameter into a text file (so I can search it).

Thank you for considering!

**Comment by pryans** [comment]
Thanks for the ideas, I'm not adding any new features to the mod at this point. Maybe I will for KCD2 if I port the mod.

You can do some of what you wanted already using cheat_eval. Search the mod homepage on nexus for the documentation on the command.
