### ISSUE TITLE
Faction Command

### ISSUE THREAD

**Issue by slopeh** [pryans/kcd-cheat#47]
First of all, thank you so much for this mod, made the game a lot more fun and a way to fix some very annoying bugs.

I found a functions for find_faction, faction_add_rep, faction_add_angriness, without a command tied to them. Would it be possible to get that in later releases? 

I would love to add it myself, but I'm an absolute pleb at programming.

**Comment by pryans** [comment]
I am not adding any new features myself anymore. If someone else codes it then I will merge it in. I tried making some faction commands a long time ago and I was never able to get it working. I also found faction functions in the code but they didn't seem to work in any way that made sense to me.
