### ISSUE TITLE
Cheat_set_time_speed ratio:

### ISSUE THREAD

**Issue by JMR1991** [pryans/kcd-cheat#5]
I believe cheat set time ratio is not working as intended. When setting the ratio to 1 the games world time scale is messed up, ie. Hunger and Exhaustion levels do not drop appropriately with their parameters. ie. 
DigestionSpeed  =  # amount of food 'lost' per world-time second (global base value)

When setting set_time_speed ratio:1 the day and night cycle changes but all values based on world time lose any sense of logic, 

I tested this with my parameters being
<row rpg_param_key="DigestionSpeed" rpg_param_value="0.001157408" />
While being on hardcore mode with the ascetic buff which multiples this parameter by .85
0.001157408 x .85 = 0.0009837968‬ so essentially at cheat_set_time_speed ratio:1 you should be losing that value every world time second, which at ratio 1 is current time, that should break down to 0.059027808 lost every minute. roughly 1 every 17 minutes. Which in reality i'm losing 1 every couple minutes. Also when resting or skipping time it opens up a whole new slew of problems in game. I've searched online and other people have said cheat_set_time_ratio has worked for them but they do not go into detail regarding these problems, if they were using it for realism someone would have mentioned having to eat food every 10 minutes in game time which makes me think somewhere along the line the script got messed up. Not to mention no one has mentioned a problem when sleeping waiting, where if you sleep or wait your nourishment and energy values no longer show a decrease or increase per hour waited until you actually wait once you do wait nearing 1 hour the game slows down to a crawl and you either have to cancel out or wait 5 or so minutes for the game to start back up, and the values for nurishment and exhaustion do not seem to match up with in game values depletion wise. Any help would be greatly appreciated as i am trying to play the game with a lessened time scale without breaking immersion. Thank you.

**Comment by pryans** [comment]
The CLI commands just make use of existing engine commands. If it doesn't work the way you want there is nothing I can do about it. I added access to them for fun.

**Comment by JMR1991** [comment]
Thanks, i got it working, its just a code that doesnt work well loaded from
inside the game, has to be loaded from the file
