### ISSUE TITLE
Does this mod currently work 1.93?

### ISSUE THREAD

**Issue by Jacuhh** [pryans/kcd-cheat#7]
Hello,

Does this mod currently work?
And if it does, then could someone write down the steps to properly install the mod, I must be doing something wrong.

Where do I put the unpacked zip.file?

I do have zero programming experience, so that might be why it won't work,, but any help would be welcome.

**Comment by hiredgunz48** [comment]
No, it doesn't appear to be working anymore, and it seems the author may have abandoned the mod. It hasn't been checked by the author to be working since 1.7

**Comment by xPaw** [comment]
I think it fails because developers have disabled access to `os`.

Removing `os.getenv` calls from `main.lua` makes it load correctly.

**Comment by pryans** [comment]
The mod loads now in 1.93. Thanks to @xPaw to pointing out the issue.
